#[macro_use]
extern crate serde_derive;
extern crate tmux_interface;

pub mod error;
pub mod keys_cfg;
pub mod pane_cfg;
pub mod panes_cfg;
pub mod project_cfg;
pub mod session_cfg;
pub mod sessions_cfg;
pub mod window_cfg;
pub mod windows_cfg;

pub use self::error::Error;
pub use self::keys_cfg::KeysCfg;
pub use self::pane_cfg::PaneCfg;
pub use self::panes_cfg::PanesCfg;
pub use self::project_cfg::ProjectCfg;
pub use self::session_cfg::SessionCfg;
pub use self::sessions_cfg::SessionsCfg;
pub use self::window_cfg::WindowCfg;
pub use self::windows_cfg::WindowsCfg;

//mod pane_cfg_tests;
//mod panes_cfg_tests;
//mod project_cfg_tests;
//mod session_cfg_tests;
//mod sessions_cfg_tests;
//mod window_cfg_tests;
//mod windows_cfg_tests;
////mod keys_cfg_tests;
//mod error_tests;

pub const PANE_ACTIVE: usize = tmux_interface::PANE_ACTIVE;
pub const PANE_AT_BOTTOM: usize = tmux_interface::PANE_AT_BOTTOM;
pub const PANE_AT_LEFT: usize = tmux_interface::PANE_AT_LEFT;
pub const PANE_AT_RIGHT: usize = tmux_interface::PANE_AT_RIGHT;
pub const PANE_AT_TOP: usize = tmux_interface::PANE_AT_TOP;
pub const PANE_BOTTOM: usize = tmux_interface::PANE_BOTTOM;
pub const PANE_CURRENT_COMMAND: usize = tmux_interface::PANE_CURRENT_COMMAND;
pub const PANE_CURRENT_PATH: usize = tmux_interface::PANE_CURRENT_PATH;
pub const PANE_DEAD: usize = tmux_interface::PANE_DEAD;
pub const PANE_DEAD_STATUS: usize = tmux_interface::PANE_DEAD_STATUS;
pub const PANE_FORMAT: usize = tmux_interface::PANE_FORMAT;
pub const PANE_HEIGHT: usize = tmux_interface::PANE_HEIGHT;
pub const PANE_ID: usize = tmux_interface::PANE_ID;
pub const PANE_IN_MODE: usize = tmux_interface::PANE_IN_MODE;
pub const PANE_INDEX: usize = tmux_interface::PANE_INDEX;
pub const PANE_INPUT_OFF: usize = tmux_interface::PANE_INPUT_OFF;
pub const PANE_LEFT: usize = tmux_interface::PANE_LEFT;
pub const PANE_MARKED: usize = tmux_interface::PANE_MARKED;
pub const PANE_MARKED_SET: usize = tmux_interface::PANE_MARKED_SET;
pub const PANE_MODE: usize = tmux_interface::PANE_MODE;
pub const PANE_PID: usize = tmux_interface::PANE_PID;
pub const PANE_PIPE: usize = tmux_interface::PANE_PIPE;
pub const PANE_RIGHT: usize = tmux_interface::PANE_RIGHT;
pub const PANE_SEARCH_STRING: usize = tmux_interface::PANE_SEARCH_STRING;
pub const PANE_START_COMMMAND: usize = tmux_interface::PANE_START_COMMMAND;
pub const PANE_SYNCHRONIZED: usize = tmux_interface::PANE_SYNCHRONIZED;
pub const PANE_TABS: usize = tmux_interface::PANE_TABS;
pub const PANE_TITLE: usize = tmux_interface::PANE_TITLE;
pub const PANE_TOP: usize = tmux_interface::PANE_TOP;
pub const PANE_TTY: usize = tmux_interface::PANE_TTY;
pub const PANE_WIDTH: usize = tmux_interface::PANE_WIDTH;

pub const PANE_NONE: usize = tmux_interface::PANE_NONE;
pub const PANE_ALL: usize = tmux_interface::PANE_ALL;

pub const WINDOW_ACTIVE: usize = tmux_interface::WINDOW_ACTIVE;
pub const WINDOW_ACTIVITY: usize = tmux_interface::WINDOW_ACTIVITY;
pub const WINDOW_ACTIVITY_FLAG: usize = tmux_interface::WINDOW_ACTIVITY_FLAG;
pub const WINDOW_BELL_FLAG: usize = tmux_interface::WINDOW_BELL_FLAG;
pub const WINDOW_BIGGER: usize = tmux_interface::WINDOW_BIGGER;
pub const WINDOW_END_FLAG: usize = tmux_interface::WINDOW_END_FLAG;
pub const WINDOW_FLAGS: usize = tmux_interface::WINDOW_FLAGS;
pub const WINDOW_FORMAT: usize = tmux_interface::WINDOW_FORMAT;
pub const WINDOW_HEIGHT: usize = tmux_interface::WINDOW_HEIGHT;
pub const WINDOW_ID: usize = tmux_interface::WINDOW_ID;
pub const WINDOW_INDEX: usize = tmux_interface::WINDOW_INDEX;
pub const WINDOW_LAST_FLAG: usize = tmux_interface::WINDOW_LAST_FLAG;
pub const WINDOW_LAYOUT: usize = tmux_interface::WINDOW_LAYOUT;
pub const WINDOW_LINKED: usize = tmux_interface::WINDOW_LINKED;
pub const WINDOW_NAME: usize = tmux_interface::WINDOW_NAME;
pub const WINDOW_OFFSET_X: usize = tmux_interface::WINDOW_OFFSET_X;
pub const WINDOW_OFFSET_Y: usize = tmux_interface::WINDOW_OFFSET_Y;
pub const WINDOW_PANES: usize = tmux_interface::WINDOW_PANES;
pub const WINDOW_SILENCE_FLAG: usize = tmux_interface::WINDOW_SILENCE_FLAG;
pub const WINDOW_STACK_INDEX: usize = tmux_interface::WINDOW_STACK_INDEX;
pub const WINDOW_START_FLAG: usize = tmux_interface::WINDOW_START_FLAG;
pub const WINDOW_VISIBLE_LAYOUT: usize = tmux_interface::WINDOW_VISIBLE_LAYOUT;
pub const WINDOW_WIDTH: usize = tmux_interface::WINDOW_WIDTH;
pub const WINDOW_ZOOMED_FLAG: usize = tmux_interface::WINDOW_ZOOMED_FLAG;

pub const WINDOW_NONE: usize = tmux_interface::WINDOW_NONE;
pub const WINDOW_ALL: usize = tmux_interface::WINDOW_ALL;

pub const SESSION_ACTIVITY: usize = tmux_interface::SESSION_ACTIVITY;
pub const SESSION_ALERTS: usize = tmux_interface::SESSION_ALERTS;
pub const SESSION_ATTACHED: usize = tmux_interface::SESSION_ATTACHED;
pub const SESSION_CREATED: usize = tmux_interface::SESSION_CREATED;
pub const SESSION_FORMAT: usize = tmux_interface::SESSION_FORMAT;
pub const SESSION_GROUP: usize = tmux_interface::SESSION_GROUP;
pub const SESSION_GROUP_LIST: usize = tmux_interface::SESSION_GROUP_LIST;
pub const SESSION_GROUP_SIZE: usize = tmux_interface::SESSION_GROUP_SIZE;
pub const SESSION_GROUPED: usize = tmux_interface::SESSION_GROUPED;
pub const SESSION_ID: usize = tmux_interface::SESSION_ID;
pub const SESSION_LAST_ATTACHED: usize = tmux_interface::SESSION_LAST_ATTACHED;
pub const SESSION_MANY_ATTACHED: usize = tmux_interface::SESSION_MANY_ATTACHED;
pub const SESSION_NAME: usize = tmux_interface::SESSION_NAME;
pub const SESSION_STACK: usize = tmux_interface::SESSION_STACK;
pub const SESSION_WINDOWS: usize = tmux_interface::SESSION_WINDOWS;

pub const SESSION_NONE: usize = tmux_interface::SESSION_NONE;
pub const SESSION_ALL: usize = tmux_interface::SESSION_ALL;
